version: '3'
services:
  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./nginx:/www/static
    depends_on:
      - web
  web:
    container_name: web
    build: .
    restart: always
    command:
      gunicorn config.wsgi -c /srv/gunicorn/gunicorn_cfg.py --chdir /www/project/ --bind 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - ./app:/www/project
