version: '3'
services:
  nginx:
    container_name: nginx
    image: ashekr/crud-webserver-nginx
    ports:
      - 80:80
    depends_on:
      - web
    links:
        - web
    logging:
      driver: awslogs
      options:
        awslogs-group: crud
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: web-nginx
  web:
    container_name: web
    image: ashekr/crud-was
    working_dir: /srv/app
    command:
      gunicorn config.wsgi:application -c /srv/gunicorn/gunicorn_cfg.py --bind 0.0.0.0:8000
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    logging:
      driver: awslogs
      options:
        awslogs-group: crud
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: was
